ExternalSecure: false
ExternalPort: 8080
Database:
  postgres:
    Host: postgres
    Port: 5432
    Database: zitadel
    User:
      Username: postgres
      Password: postgres
    SSL:
      Mode: disable
FirstInstance:
  Org:
    Human:
      Username: "admin@example.com"
      Password: "admin1" 
